MedicalConsultation/MedicalConsultation.ControlPanel/ViewModels/Shared/TableRawViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MedicalConsultation.ControlPanel.ViewModels.Shared
{
    public class TableRawViewModel<TDto>
    {
        public TableRawViewModel(TDto data, bool hasPremmissions, bool hasPremmissionToDelete, bool hasPremmissionToEdit)
        {
            HasPremmissions = hasPremmissions;
            HasPremmissionToDelete = hasPremmissionToDelete;
            HasPremmissionToEdit = hasPremmissionToEdit;
            RowData = data;
        }
        public TDto RowData { get; }
        public bool HasPremmissions { get; }
        public bool HasPremmissionToDelete { get; }
        public bool HasPremmissionToEdit { get; }
    }
}

MedicalConsultation/MedicalConsultation.ControlPanel/Controllers/ConsultationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

using MedicalConsultation.ControlPanel.Helpers.Renders;
using MedicalConsultation.ControlPanel.ViewModels.Consultation;
using MedicalConsultation.ControlPanel.ViewModels.Shared;
using MedicalConsultation.Helpers;
using MedicalConsultation.Services.Core.Consultation;
using MedicalConsultation.Services.Shared.Enum;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MedicalConsultation.ControlPanel.Controllers
{
    [Authorize(Roles = "Administrator,Patient")]
    public class ConsultationController : BaseController
    {
        private readonly IConsultationRepository _consultationRepository;
        private readonly IPartialViewRender _partialViewRender;
        public ConsultationController(IConsultationRepository consultationRepository, IPartialViewRender partialViewRender)
        {
            _consultationRepository = consultationRepository;
            _partialViewRender = partialViewRender;
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Index(bool markedAsDone = false)
        {
            var vm = new IndexViewModel("Consultation management", "Med. Consult.")
            {
                ModalViewModel = new ViewModels.ModalViewModel()
                {
                    ModalTitle = "Reply for a consultation"
                }
            };
            ViewData["MarkedAsDone"] = markedAsDone;
            if (markedAsDone)
            {
                ViewData["ConsultationStatus"] = "Already answered";
                vm.AddConsultations(_consultationRepository.GetConsultationsMarkedAsDone());
            }
            else
            {
                ViewData["ConsultationStatus"] = "Waiting for an answer";
                vm.AddConsultations(_consultationRepository.GetConsultationsWaitingToBeAnswered());
            }

            return View(vm);
        }

        [Authorize(Roles = "Patient")]
        public IActionResult PatientConsultations()
        {
            var vm = new IndexViewModel("My consultation", "Med. Consult.")
            {
                ModalViewModel = new ViewModels.ModalViewModel()
                {
                    ModalTitle = "Ask a doctor"
                }
            };
            vm.AddConsultations(_consultationRepository.GetPatientConsultation(User.FindFirstValue(ClaimTypes.NameIdentifier)));

            return View(vm);
        }

        [Authorize(Roles = "Administrator,Patient")]
        public IActionResult MyConsultationDetails(int id)
        {
            var consultationDetails = _consultationRepository.GetConsultation(id);
            if (consultationDetails is null)
            {
                return RedirectToAction("Index", "Home");
            }

            var vm = new MyConsultationDetailsViewModel()
            {
                ConsultationId = consultationDetails.ConsultationId,
                Content = consultationDetails.Content,
                IssuedOn = consultationDetails.IssuedOn,
                MarkedAsDone = consultationDetails.MarkedAsDone,
                PatientId = consultationDetails.PatientId,
                Subject = consultationDetails.Subject,
                Replies = consultationDetails.Replies,
                IsAdmin = User.IsInRole("Administrator")
            };
            if (vm.PatientId == User.FindFirstValue(ClaimTypes.NameIdentifier)
                &&
                !vm.IsAdmin)
            {
                _consultationRepository.MarkConsultationRepliesAsSeen(id);
            }
            return View(vm);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult GetConsultReplyForm(int id)
        {
            if (IsNotAjaxRequest())
            {
                return NotFound();
            }
            var formVM = new ConsultationReplyFormViewModel()
            {
                AdminID = User.FindFirstValue(ClaimTypes.NameIdentifier),
                ConsultationID = id
            };


            return PartialView(PartialPathProvider.ConsultationReplyForm, formVM);
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult GetConsultReplyIndexDatatable(bool markedAsDone)
        {
            if (IsNotAjaxRequest())
            {
                return NotFound();
            }
            var data = markedAsDone ? _consultationRepository.GetConsultationsMarkedAsDone() : _consultationRepository.GetConsultationsWaitingToBeAnswered();

            var rawPartialViewModel = data.Select(mt => new TableRawViewModel<ConsultationDto>(mt, true, false, false));
            try
            {
                return GetSuccessJsonResult("Updating datatable - successed!", "The datatable has been updated successfully with the new data!", new
                {
                    TableRows = rawPartialViewModel.Select(async row => await _partialViewRender.GetViewAsTextAsync(row, PartialPathProvider.ConsultationTableRow))
                });
            }
            catch
            {
                return GetFailureJsonResult("Saving consultation successed but! :(", "We couldn't refresh the table, please refresh the page!");
            }
        }


        [HttpGet]
        [Authorize(Roles = "Patient")]
        public IActionResult GetIndexDatatable()
        {
            if (IsNotAjaxRequest())
            {
                return NotFound();
            }
            var patientConsultations = _consultationRepository.GetPatientConsultation(User.FindFirstValue(ClaimTypes.NameIdentifier));

            var rawPartialViewModel = patientConsultations.Select(mt => new TableRawViewModel<ConsultationDto>(mt, true, false, false));
            try
            {
                return GetSuccessJsonResult("Updating datatable - successed!", "The datatable has been updated successfully with the new data!", new
                {
                    TableRows = rawPartialViewModel.Select(async row => await _partialViewRender.GetViewAsTextAsync(row, PartialPathProvider.PatientConsultTableRow))
                });
            }
            catch
            {
                return GetFailureJsonResult("Saving consultation successed but! :(", "We couldn't refresh the table, please refresh the page!");
            }
        }

        [Authorize(Roles = "Patient")]
        public IActionResult GetConsultForm(int id)
        {
            if (IsNotAjaxRequest())
            {
                return NotFound();
            }
            var formVM = new ConsultationFormViewModel()
            {
                MarkedAsDone = false,
                PatientId = User.FindFirstValue(ClaimTypes.NameIdentifier)
            };

            if (id == 0)
            {
                return PartialView(PartialPathProvider.ConsultationForm, formVM);
            }

            var entityResult = _consultationRepository.GetConsultation(id);
            if (entityResult is null)
            {
                return GetFailureJsonResult("Doesn't exist", "There's consultation with this ID");
            }

            formVM.ConsultationId = entityResult.ConsultationId;
            formVM.Content = entityResult.Content;
            formVM.IssuedOn = entityResult.IssuedOn;
            formVM.MarkedAsDone = entityResult.MarkedAsDone;
            formVM.PatientId = entityResult.PatientId;
            formVM.HistoricalInformation = entityResult.HistoricalInformation;
            formVM.Subject = entityResult.Subject;

            return PartialView(PartialPathProvider.ConsultationForm, formVM);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Patient")]
        public async Task<IActionResult> ConsultAction(ConsultationFormViewModel formVM)
        {
            if (IsNotAjaxRequest())
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return GetFailureJsonResult("Form is invalid", "Please fix the form error!");
            }
            var actionOperationType = formVM.ConsultationId == 0 ? ActionOperationType.Create : ActionOperationType.Update;

            var data = new ConsultationFormDto(actionOperationType)
            {
                ConsultationId = formVM.ConsultationId,
                Content = formVM.Content,
                IssuedOn = formVM.IssuedOn,
                MarkedAsDone = formVM.MarkedAsDone,
                PatientId = formVM.PatientId,
                HistoricalInformation = formVM.HistoricalInformation,
                Subject = formVM.Subject
            };

            var result = _consultationRepository.Action(data);

            if (result is null)
            {

                return GetFailureJsonResult("Saving consultation - failed :(", $"Could not save the consultation try again.");
            }

            var returnedData = _consultationRepository.GetConsultation(result.ConsultationId);
            var rawPartialViewModel = new TableRawViewModel<ConsultationDto>(returnedData, true, false, false);

            try
            {
                return GetSuccessJsonResult("Saving consultation - success! ", $"Your consultation <b>{data.Subject} </b> has been saved successfully!", new
                {
                    TableRaw = await _partialViewRender.GetViewAsTextAsync(rawPartialViewModel, PartialPathProvider.PatientConsultTableRow),
                    Data = returnedData
                });
            }
            catch
            {
                return GetFailureJsonResult("Saving consultation successed but! :(", "We couldn't refresh the table, please refresh the page!");
            }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]

MedicalConsultation/MedicalConsultation.ControlPanel/ViewComponents/HeaderViewComponent.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

using MedicalConsultation.ControlPanel.ViewModels;
using MedicalConsultation.Helpers;

using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;

namespace MedicalConsultation.ControlPanel.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var requestFeature = HttpContext.Features.Get<IHttpRequestFeature>();
            var processedRawUrl = requestFeature.RawTarget.EndsWith('/') || requestFeature.RawTarget.EndsWith('\\') ?
                                    requestFeature.RawTarget : $"{requestFeature.RawTarget}/";
            var forwardPosition = processedRawUrl.Length > 1 ? processedRawUrl.IndexOf('/', 1) : processedRawUrl.IndexOf('/');
            var rawUrl = processedRawUrl.Substring(forwardPosition == -1 ? 0 : forwardPosition);
            return View(ViewComponentPathProvider.Header, new HeaderComponentViewModel()
            {
                RegionCultureInfo = new List<Tuple<RegionInfo, CultureInfo>>
                {
                    new Tuple<RegionInfo, CultureInfo>(new RegionInfo("en-US"), new CultureInfo("en")),
                    new Tuple<RegionInfo, CultureInfo>(new RegionInfo("ar-SA"), new CultureInfo("ar"))
                },
                RawUrl = rawUrl,
                RequestHostHeader = requestFeature.Headers["host"],
                RequestScheme = requestFeature.Scheme
            });
        }
    }
}

MedicalConsultation/MedicalConsultation.ControlPanel/ViewComponents/SidebarViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using MedicalConsultation.ControlPanel.ViewModels;
using MedicalConsultation.Database.Entities;
using MedicalConsultation.Helpers;

using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MedicalConsultation.ControlPanel.ViewComponents
{
    public class SidebarViewComponent : ViewComponent
    {

        private readonly UserManager<MCIdentityUser> _userManager;
        public SidebarViewComponent(UserManager<MCIdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            var userRole = await _userManager.GetRolesAsync(user);
            return View(ViewComponentPathProvider.Sidebar, new SidebarComponentViewModel
            {
                Username = user.UserName,
                FullName = $"{user.FirstName} {user.LastName}",
                Role = userRole.FirstOrDefault()
            }) ;
        }
    }
}

MedicalConsultation/MedicalConsultation.ControlPanel/Views/Shared/_ActionModal.cshtml
@model ModalViewModel

<div class="modal fade" id="@($"{Model.IdPrefix}actionModal")">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body p-0" id="@($"{Model.IdPrefix}actionModalBody")">

            </div>
            <div class="modal-footer p-0" style="background:rgba(0, 0, 0, 0.00)">
                <button type="button"
                        id="@($"{Model.IdPrefix}closeModalButton")"
                        class="btn btn-sm btn-outline-danger btn-block waves-effect action-button">
                    <i class="fas fa-close pr-1"></i>
                    <span class="action-button-text pr-0"> @FromResx["Finish"]</span>
                    <i class="fas fa-cog fa-spin action-button-loader" style="display:none;"></i>
                </button>
            </div>
        </div>
    </div>
</div>

MedicalConsultation/MedicalConsultation.ControlPanel/Views/Shared/_Footer.cshtml
    <footer class="main-footer small">

        <!-- Default to the left -->
        @FromResx["Developed by"] <a href="mailto:wael_134002@svuonline.org">@FromResx["Wael Alshabani"]</a> and  <a href="mailto:mhd_ali_133905@svuonline.org">@FromResx["Mhd Ali Faour"]</a> as AWP homework, Master of Web science program @@ Syrian Virtual Universty
    </footer>

MedicalConsultation/MedicalConsultation.ControlPanel/Views/Shared/_IdentityLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link href="~/lib/icheck-bootstrap/icheck-bootstrap.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/theme/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <style>
        html {
            height: 100%;
        }

        body {
            height: 100%;
            margin: 0;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background: linear-gradient(#604cc4, #0d033f) !important;
        }

        .form-control.is-invalid {
            background-image: none !important;
        }

        .was-validated .custom-select:valid {
            background-image: none !important;
        }


        .was-validated .custom-select:invalid {
            background-image: none !important;
        }

        .valid-feedback.feedback-icon,
        .invalid-feedback.feedback-icon {
            display:none;
        }
    </style>
    @RenderSection("Styles", required: false)
</head>
<body class="hold-transition login-page">
    @RenderBody()

    <footer>
        <div class="text-center text-white text-sm-center">
            @FromResx["Developed by"] <a class="text-white" href="mailto:wael_134002@svuonline.org">@FromResx["Wael Alshabani"]</a> and <a class="text-white" href="#">@FromResx["Mhd Ali Faour"]</a> as AWP homework <br />
            Master of Web science program <br /> 
            @@ <a href="https://www.svuonline.org/">Syrian Virtual Universty</a>
        </div>
    </footer>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/theme/adminlte.min.js"></script>

    <script src="~/lib/underscore.js/underscore-min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/izitoast/js/iziToast.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script type="module" src="~/lib/backhelpers/bundle.js"></script>

    @RenderSection("Scripts", false)
</body>
</html>

MedicalConsultation/MedicalConsultation.ControlPanel/Views/Shared/_Layout.cshtml
@model BaseViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> @Model.PageTitle | @Model.ApplicationName </title>
    <partial name="@PartialPathProvider.ThemeStylePartial" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap-reboot.min.css" rel="stylesheet" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/flag-icon-css/css/flag-icon.css" rel="stylesheet" />
    <link href="~/lib/izitoast/css/iziToast.min.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/select2-bootstrap-theme/select2-bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)

</head>
<body class="hold-transition sidebar-mini" data-page-language="@Model.PageLanguage" data-app-default-language="@Model.DefaultLanguage">
    <div class="wrapper">
        <vc:sidebar></vc:sidebar>
        <vc:header></vc:header>
        <main role="main" class="content-wrapper">
            @RenderBody()
        </main>

        <partial name="@PartialPathProvider.FooterPartial" />
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <partial name="@PartialPathProvider.ThemeScriptPartial" />
    <script src="~/lib/underscore.js/underscore-min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/izitoast/js/iziToast.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script type="module" src="~/lib/backhelpers/bundle.js"></script>
    @RenderSection("Scripts", required: false)

    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

MedicalConsultation/MedicalConsultation.ControlPanel/Views/Shared/_PatientLayout.cshtml
@model BaseViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> @Model.PageTitle | @Model.ApplicationName </title>
    <partial name="@PartialPathProvider.ThemeStylePartial" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap-reboot.min.css" rel="stylesheet" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/flag-icon-css/css/flag-icon.css" rel="stylesheet" />
    <link href="~/lib/izitoast/css/iziToast.min.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/select2-bootstrap-theme/select2-bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
    <style>
        #custom-color {
            background: rgb(144,139,240);
            background: linear-gradient(117deg, rgba(144,139,240,1) 0%, rgba(107,107,238,1) 18%, rgba(138,46,165,0.7738445720084909) 72%, rgba(0,212,255,1) 100%);
        }
    </style>
</head>
<body class="hold-transition layout-top-nav" data-page-language="@Model.PageLanguage" data-app-default-language="@Model.DefaultLanguage">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
            <div class="container">
                <a asp-action="Index" asp-controller="Home" class="navbar-brand">
                    <span class="brand-text font-weight-light display-4"><strong>Med. Consult.</strong></span>
                </a>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a asp-action="About" asp-controller="Home" class="nav-link">About</a>
                    </li>
                    <li class="nav-item">
                    <li class="nav-item">
                        <a asp-controller="Consultation" asp-action="PatientConsultations" class="nav-link">My consultations</a>
                    </li>
                </ul>
                <!-- Right navbar links -->
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item mr-1">
                            <span class="text-sm">Welcome</span> <a asp-action="Index" asp-controller="Home" class=" badge badge-primary"> @User.Identity.Name</a>
                        </li>
                        <li class="nav-item ml-1">
                            <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button style="border: none; margin:0px;" type="submit" class="badge badge-danger">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-area="Identity" asp-page="/Account/Login" class="nav-link btn btn-navbar mr-1">Login</a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Identity" asp-page="/Account/Register" class="nav-link btn btn-navbar mr-1">Register</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
        <!-- /.navbar -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                <div class="container">
                    <!-- /.row -->
                    <div class="row">
                        <div class="col-md-12">
                            @RenderBody()
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <partial name="@PartialPathProvider.FooterPartial" />

    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <partial name="@PartialPathProvider.ThemeScriptPartial" />
    <script src="~/lib/underscore.js/underscore-min.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/lib/izitoast/js/iziToast.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script type="module" src="~/lib/backhelpers/bundle.js"></script>
    @RenderSection("Scripts", required: false)

    <script src="~/js/site.js" asp-append-version="true"></script>

</body>
</html>

MedicalConsultation/MedicalConsultation.ControlPanel/Views/Shared/_ThemeScripts.cshtml
<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="~/lib/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE -->
<script src="~/js/theme/adminlte.min.js"></script>

MedicalConsultation/MedicalConsultation.ControlPanel/Views/Shared/_ThemeStyle.cshtml
<!-- Font Awesome Icons -->
<link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
<!-- IonIcons -->
<link rel="stylesheet" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link href="~/css/theme/adminlte.min.css" rel="stylesheet" />
<!-- Google Font: Source Sans Pro -->
<link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">