MedicalConsultation/MedicalConsultation.ControlPanel/ViewModels/MedicalTopic/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MedicalConsultation.ControlPanel.ViewModels.Shared;
using MedicalConsultation.Services.Core.Topic;

namespace MedicalConsultation.ControlPanel.ViewModels.MedicalTopic
{
    public class IndexViewModel : BaseViewModel
    {
        public IndexViewModel(string pageTitle, string applicationName ="Med. Conult.", string pageLanguage = "en", string defaultLangauge = "en") : base(pageTitle, applicationName, pageLanguage, defaultLangauge)
        {
        }

        public IEnumerable<MedicalTopicDto> MedicalTopics { get; private set; }
        public bool HasMedicalTopics => MedicalTopicsCount > 0;
        public int MedicalTopicsCount => MedicalTopics.Count();

        public ModalViewModel ModalViewModel { get; set; }

        internal void AddMedicalTopics(IEnumerable<MedicalTopicDto> data)
        {
            MedicalTopics = data ?? new List<MedicalTopicDto>();
        }

        public TableRawViewModel<MedicalTopicDto> GetTableRawViewModel(MedicalTopicDto dto, bool hasPremessions = true, bool canDelete = true, bool canEdit = true)
        {
            return new TableRawViewModel<MedicalTopicDto>(dto, hasPremessions, canDelete, canEdit);
        }

    }
}

MedicalConsultation/MedicalConsultation.ControlPanel/ViewModels/MedicalTopic/MedicalTopicFormViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MedicalConsultation.ControlPanel.ViewModels.MedicalTopic
{
    public class MedicalTopicFormViewModel
    {
        public int MedicalTopicID { get; set; }

        public string Title { get; set; }
        public string Description { get; set; }

        public DateTime IssueDate { get; set; } = DateTime.UtcNow;
        public int NumberOfVisits { get; set; }

        public string AdminID { get; set; }
        public string AdminFullName { get; set; }
        public string ImageUrl { get; set; }
        public IFormFile Image { get; set; }

        public IEnumerable<SelectListItem>  Admins { get; set; }
    }
}

MedicalConsultation/MedicalConsultation.ControlPanel/ViewModels/MedicalTopicDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MedicalConsultation.ControlPanel.ViewModels
{
    public class MedicalTopicDetailsViewModel : BaseViewModel
    {
        public MedicalTopicDetailsViewModel(string pageTitle = "Medical Topic",
            string applicationName = "Med. Consult.",
            string pageLanguage = "en", string defaultLangauge = "en")
            : base(pageTitle, applicationName, pageLanguage, defaultLangauge)
        {
        }


        public int MedicalTopicID { get; set; }

        public string Title { get; set; }
        public string Description { get; set; }

        public DateTime IssueDate { get; set; }
        public int NumberOfVisits { get; set; }
        public string ImageURL { get; set; }
        public string AdminID { get; set; }
        public string AdminFullName { get; set; }
    }
}

MedicalConsultation/MedicalConsultation.ControlPanel/Controllers/MedicalTopicController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

using MedicalConsultation.ControlPanel.Helpers.Renders;
using MedicalConsultation.ControlPanel.ViewModels;
using MedicalConsultation.ControlPanel.ViewModels.MedicalTopic;
using MedicalConsultation.ControlPanel.ViewModels.Shared;
using MedicalConsultation.Helpers;
using MedicalConsultation.Services.Core.MedicalTopic;
using MedicalConsultation.Services.Core.Topic;
using MedicalConsultation.Services.Shared.Enum;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MedicalConsultation.ControlPanel.Controllers
{
    [Authorize(Roles = "Administrator,Patient")]
    public class MedicalTopicController : BaseController
    {
        private readonly IMedicalTopicRepository _medicalTopicRepository;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IPartialViewRender _partialViewRender;
        public MedicalTopicController(IMedicalTopicRepository medicalTopicRepository, 
            IPartialViewRender partialViewRender,
            IHostingEnvironment hostingEnvironment)
        {
            _medicalTopicRepository = medicalTopicRepository;
            _partialViewRender = partialViewRender;
            _hostingEnvironment = hostingEnvironment;
        }

        [AllowAnonymous]
        public IActionResult MedicalTopicDetails(int? id)
        {
            if (id is null || id.Value == 0)
            {
                return RedirectToActionPermanent("Index", "Home");
            }

            _medicalTopicRepository.IncreateVisitNumber(id.Value);
            var mt = _medicalTopicRepository.GetMedicalTopic(id.Value);

            var vm = new MedicalTopicDetailsViewModel()
            {
                AdminFullName = mt.AdminFullName,
                AdminID = mt.AdminID,
                Description = mt.Description,
                IssueDate = mt.IssueDate,
                MedicalTopicID = mt.MedicalTopicID,
                NumberOfVisits = mt.NumberOfVisits,
                Title = mt.Title,
                ImageURL = mt.ImageURL
            };
            return View(vm);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Index()
        {
            var vm = new ViewModels.MedicalTopic.IndexViewModel("Medical topics management")
            {
                ModalViewModel = new ViewModels.ModalViewModel()
                {
                    ModalTitle = "Create medical topic"
                }
            };

            vm.AddMedicalTopics(_medicalTopicRepository.GetMedicalTopics());
            return View(vm);
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult GetLoggedInAdmin()
        {
            if (IsNotAjaxRequest())
            {
                return NotFound();
            }
            return Json(new List<object>
            {
                new 
                {
                    Username = User.FindFirst(ClaimTypes.Name).Value,
                    UserId = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                }
            });
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult GetMedicalTopicForm(int id)
        {
            if (IsNotAjaxRequest())
            {
                return NotFound();
            }
            var formVM = new MedicalTopicFormViewModel();

            if (id == 0)
            {
                return PartialView(PartialPathProvider.MedicalTopicForm, formVM);
            }

            var entityResult = _medicalTopicRepository.GetMedicalTopic(id);
            if (entityResult is null)
            {
                return GetFailureJsonResult("Doesn't exist", "There's medical topic with this ID");
            }

            formVM.AdminFullName = entityResult.AdminFullName;
            formVM.AdminID = entityResult.AdminID;
            formVM.Description = entityResult.Description;
            formVM.IssueDate = entityResult.IssueDate;
            formVM.MedicalTopicID = entityResult.MedicalTopicID;
            formVM.NumberOfVisits = entityResult.NumberOfVisits;
            formVM.Title = entityResult.Title;
            formVM.ImageUrl = entityResult.ImageURL;
            formVM.Admins = new List<SelectListItem>()
            {
                new SelectListItem()
                {
                    Text = entityResult.AdminFullName,
                    Value = entityResult.AdminID,
                    Selected = true
                }
            };

            return PartialView(PartialPathProvider.MedicalTopicForm, formVM);
        }


        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public IActionResult GetIndexDatatable()
        {
            if (IsNotAjaxRequest())
            {
                return NotFound();
            }
            var medicalTopics = _medicalTopicRepository.GetMedicalTopics();
            var rawPartialViewModel = medicalTopics.Select(mt => new TableRawViewModel<MedicalTopicDto>(mt, true, true, true));
            try
            {
                return GetSuccessJsonResult("Updating datatable - successed!", "The datatable has been updated successfully with the new data!", new
                {
                    TableRows = rawPartialViewModel.Select(async row => await _partialViewRender.GetViewAsTextAsync(row, PartialPathProvider.MedicalTopicTableRow))
                });
            }
            catch
            {
                return GetFailureJsonResult("Saving medical topic successed but! :(", "We couldn't refresh the table, please refresh the page!");
            }
        }

        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                      + "_"
                      + Guid.NewGuid().ToString().Substring(0, 4)
                      + Path.GetExtension(fileName);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Action(MedicalTopicFormViewModel formVM)
        {
            if (IsNotAjaxRequest())
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return GetFailureJsonResult("Form is invalid", "Please fix the form error!");
            }
            var actionOperationType = formVM.MedicalTopicID == 0 ? ActionOperationType.Create : ActionOperationType.Update;
            string uniqueFileName = string.Empty;
            if (formVM.Image != null)
            {
                uniqueFileName = GetUniqueFileName(formVM.Image.FileName);
                var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "images/uploads");
                var filePath = Path.Combine(uploads, uniqueFileName);
                formVM.Image.CopyTo(new FileStream(filePath, FileMode.Create));

                //to do : Save uniqueFileName  to your db table   
            }

            var data = new MedicalTopicFormDto(actionOperationType)
            {
                AdminID = formVM.AdminID,
                Description = formVM.Description,
                IssueDate = formVM.IssueDate,
                MedicalTopicID = formVM.MedicalTopicID,
                NumberOfVisits = formVM.NumberOfVisits,
                Title = formVM.Title,
                ImageURL = uniqueFileName
            };

            var result = _medicalTopicRepository.Action(data);

            if (result is null)
            {

                return GetFailureJsonResult("Saving medical topic - failed :(", $"Could not save the medical topic try again.");
            }

            var returnedData = _medicalTopicRepository.GetMedicalTopic(result.MedicalTopicID);
            var rawPartialViewModel = new TableRawViewModel<MedicalTopicDto>(returnedData, true, true, true);

            try
            {
                return GetSuccessJsonResult("Saving medical topic - success! ", $"Your medical topic <b>{data.Title} </b> has been saved successfully!", new
                {
                    TableRaw = await _partialViewRender.GetViewAsTextAsync(rawPartialViewModel, PartialPathProvider.MedicalTopicTableRow),
                    Data = returnedData
                });
            }
            catch
            {
                return GetFailureJsonResult("Saving medical topic successed but! :(", "We couldn't refresh the table, please refresh the page!");
            }
        }


        [HttpDelete]
        [Authorize(Roles = "Administrator")]
        public IActionResult Remove(int id)
        {
            try
            {
                if (IsNotAjaxRequest())
                {
                    return NotFound();
                }
                if (id == 0)
                {
                    return GetFailureJsonResult("Remove medical topic - failed :(", "Your id is null.");
                }
                var removeResult = _medicalTopicRepository.Remove(id);
                if (!removeResult)
                {
                    return GetFailureJsonResult("Remove medical topic - failed :(", "");
                }
            }
            catch (Exception)
            {
                return GetFailureJsonResult("Remove medical topic - failed :(", "Your id is null.");

            }
            return GetSuccessJsonResult("Remove medical topic - successed!", "The medical topic has been deleted successfully!");
        }

    }
}

MedicalConsultation/MedicalConsultation.ControlPanel/Views/MedicalTopic/Index.cshtml
@model MedicalConsultation.ControlPanel.ViewModels.MedicalTopic.IndexViewModel
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-xl-6">
                <h1 class="m-t-3">@FromResx["Medical Topic Management"]</h1>
            </div>
            <div class="col-xl-6">
                <ol class="breadcrumb float-sm-right text-sm">
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">@FromResx["Dashboard"]</a></li>
                    <li class="breadcrumb-item active"><a class="text-muted" asp-controller="MedicalTopic" asp-action="Index">@FromResx["Medical topics management page"]</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- /.content-header -->
<!-- Main content -->
<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">

                <div class="row">
                    <div class="col-12">
                        <div class="card-tools">
                            <a id="createButton" href="#"
                               data-get-url="@Url.Action("GetMedicalTopicForm", "MedicalTopic")"
                               data-toggle="modal" data-target="#actionModal"
                               data-backdrop="static" data-keyboard="false"
                               class="btn btn-sm btn-success">@FromResx["Create new medical topic"]</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="indexDataTable"
                       data-remove-url="@Url.Action("Remove", "MedicalTopic")"
                       data-update-datatable-url="@Url.Action("GetIndexDatatable", "MedicalTopic")"
                       data-confirm-title-msg="@FromResx["Deleting a medical topic!"]"
                       data-confirm-message-msg="@($"{FromResx["Are you sure you want to delete this topic?\n Medical topic title: "].Value} ")"
                       data-confirm-ok-btn-msg="@FromResx["Yes"]"
                       data-confirm-cancel-btn-msg="@FromResx["No, take me back!"]"
                       class="table table-striped table-hover dt-responsive " style="width:100%">

                    <thead>
                        <tr>
                            <th>@FromResx["Title"]</th>
                            <th>@FromResx["Admin name"]</th>
                            <th>@FromResx["Description"]</th>
                            <th>@FromResx["Issue date"]</th>
                            <th>@FromResx["Management tools"]</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var tr in Model.MedicalTopics)
                        {
                            <partial name="@PartialPathProvider.MedicalTopicTableRow"
                                     model="Model.GetTableRawViewModel(tr)" />
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>
<!-- /.content -->

<partial name="@PartialPathProvider.ActionModalPartial" model="Model.ModalViewModel" />


@section Styles {
    <link href="~/lib/datatables/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/DataTables/Responsive-2.2.3/css/responsive.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/DataTables/FixedColumns-3.3.0/css/fixedColumns.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/DataTables/SearchPanes-1.0.1/css/searchPanes.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/filePond/filepond.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
    <link href="https://unpkg.com/filepond-plugin-image-edit/dist/filepond-plugin-image-edit.css" rel="stylesheet">
    <link href="https://unpkg.com/filepond-plugin-file-poster/dist/filepond-plugin-file-poster.css" rel="stylesheet">
}

@section Scripts {

    <script src="~/lib/datatables/DataTables/datatables.min.js"></script>
    <script src="~/lib/datatables/DataTables/Responsive-2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script src="~/lib/datatables/DataTables/FixedColumns-3.3.0/js/fixedColumns.bootstrap4.min.js"></script>
    <script src="~/lib/datatables/DataTables/SearchPanes-1.0.1/js/searchPanes.bootstrap4.min.js"></script>
    <script src="~/lib/filePond/filepond.min.js"></script>

    <script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-validate-size/dist/filepond-plugin-image-validate-size.js"></script>
    <script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"></script>
    <script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"></script>
    <script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-crop/dist/filepond-plugin-image-crop.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-resize/dist/filepond-plugin-image-resize.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-edit/dist/filepond-plugin-image-edit.js"></script>
    <script src="https://unpkg.com/filepond-plugin-file-poster/dist/filepond-plugin-file-poster.js"></script>
    <script type="module" src="~/js/views/medicalTopics/index.js"></script>
}

MedicalConsultation/MedicalConsultation.ControlPanel/Views/MedicalTopic/MedicalTopicDetails.cshtml
@model MedicalTopicDetailsViewModel
@{
    Layout = PartialPathProvider.PatientLayout;
    var random = new Random();
    var color = String.Format("{0:X6}", random.Next(0x1000000));
}


<div class="card card-primary card-outline mt-5">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fas fa-edit"></i>
            Medical Topic Details
        </h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-md-5">
                <h4>@Model.Title </h4>
                <hr />
                <span class="text-muted mb-2 pb-3"> Issued by  <span class="badge badge-info">@Model.AdminFullName</span> <small> at </small> <span class="font-italic">@Model.IssueDate.ToShortDateString()</span> </span>
                <br />
                <p class="text-sm text-muted">viewed <span class="badge badge-pill badge-success ">@Model.NumberOfVisits</span> times</p>
                <p>
                    @Model.Description
                </p>
            </div>
            <div class="col-12 col-md-7">
                @if (!string.IsNullOrEmpty(Model.ImageURL))
                {
                    <img src="@Url.Content($"~/images/uploads/{Model.ImageURL}")" class="card-img-top" />
                }
                else
                {
                    <img src="@($"https://dummyimage.com/600x400/{color}/ffffff&text=+")" class="card-img-top" alt="...">
                }
            </div>
        </div>
    </div>
    <!-- /.card -->
</div>